# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Building
        run: |
          yarn
          yarn tsc
      - name: Archive project artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
          retention-days: 1
          name: project-artifact

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Downloading artifact
        uses: actions/download-artifact@v3
        with:
          name: project-artifact
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publishing to npm
        run: yarn publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
